const productsWeek = [
    {id:1,
    name:"Cooling Base",
    description:"Special for 24-hour work. Protect your laptop. With 5 adjustable angles, play...",
    tag:["COOLER","ACCESSORIES"],
    price:49.99,
    src:"images/products/section1/coolingBase.png",
    alt: "Cooling Base",
    id2: "coolingBase",},

    {id:2,
    name:"Nvida gtx 1060",
    description:"Video card nvida gtx 1060. With 8GB of memory, you can play all the games...",
    tag:["NVIDIA","COMPONENTS"],
    price:399.99,
    src:"images/products/section1/videoCard1.png",
    alt: "Video Card 1",
    id2: "videoCard1",},
    
    {id:3,
    name:"Amd rx 1070",
    description:"Video card amd rx 1070. With 8GB of memory, you can play all the games...",
    tag:["AMD","COMPONENTS"],
    price:299.99,
    src:"images/products/section1/videoCard2.png",
    alt: "Video Card 2",
    id2: "videoCard2"},

    {id:4,
    name:"Combo Glaze Gaming",
    description:"Mouse and keyboard combo. With RGB, compatible with all the games...",
    tag:["ACCESSORIES","COMPONENTS"],
    price:69.99,
    src:"images/products/section1/keyboard.png",
    alt: "Keyboard",
    id2: "keyboard"},

    {id:5,
    name:"Mouse Gaming",
    description:"Mouse with RGB. With RGB, compatible with all the games...",
    tag:["ACCESSORIES","COMPONENTS"],
    price:24.99,
    src:"images/products/section1/mouse.png",
    alt: "Mouse",
    id2: "mouse"},
]

const productsPersonalized = [
    {id:1,
    name:"Devastator GC550",
    description:"The devastator has room for six fans, two mechanical and two solid disks; it has seven slots", 
    tag:["CASES","ACCESSORIES"],
    price:39.75,
    src:"images/products/section2/casesRGB3.png",
    alt: "Case RGB 3",
    id2: "casesRGB3"},

    {id:2,
    name:"Tailgate GC702",
    description:"Designed for pc lovers who want a stylish chassis. Beautifully constructed with...",
    tag:["CASES","ACCEESORIES"],
    price:66.50,
    src:"images/products/section2/casesRGB.png",    
    alt: "Cases RGB",
    id2: "casesRGB",},
    
    {id:3,
    name:"Terminator 2000",
    description:"The terminator has room for nine fans, four mechanical and two solid disks; it has seven slots",
    tag:["CASES","ACCEESORIES"],
    price:299.99,
    src:"images/products/section2/casesRGB2.png",    
    alt: "Cases RGB 2",
    id2: "casesRGB2",},

    {id:4,
    name:"Cooling RGB",
    description:"Kit of cooling RGB. With 5 fan RGB. VAT included...",
    tag:["COMPONENTS"],
    price:24.99,
    src:"images/products/section2/coolingRGB.png",    
    alt: "Cooling RGB",
    id2: "coolingRGB",},  

    {id:5,
    name:"Tower Fan 12cm RGB",
    description:"Gamer tower fan 12cm rgb nicols double color ring. VAT included.",
    tag:["COMPONENTS"],
    price:24.99,
    src:"images/products/section2/fanRGB.png",    
    alt: "Fan RGB",
    id2: "fanRGB",},  
]

